# Generated by Django 2.1 on 2018-09-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portafolio_site',
            new_name='portfolio_site',
        ),
    ]
